sudo: required
language: minimal

services:
  - docker

before_install:
  - docker build -t evearakaki/verdadeiro-gamersclub .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: dev