version: "2"
services:
    database-mongodb:
        mem_limit: 2G
        container_name: database-mongodb
        env_file: ./.infra/mongodb/development.env
        image: mongo:4
        volumes:
            - ./storage/mongodb/current:/data/db
    app-server:
        mem_limit: 2G
        container_name: app
        env_file: ./.infra/app/development.env
        image: app-server
        build:
            dockerfile: ./.infra/app/development.dockerfile
            context: .
        volumes:
            - ./app:/root/workspace/app
        depends_on:
            - database-mongodb